-- First, let's add some sample profiles for doctors
INSERT INTO public.profiles (user_id, email, full_name, phone, gender) VALUES
  (gen_random_uuid(), 'dr.smith@example.com', 'Dr. Sarah Smith', '+254700123456', 'female'),
  (gen_random_uuid(), 'dr.johnson@example.com', 'Dr. Michael Johnson', '+254700123457', 'male'),
  (gen_random_uuid(), 'dr.ochieng@example.com', 'Dr. Grace Ochieng', '+254700123458', 'female'),
  (gen_random_uuid(), 'dr.kiprop@example.com', 'Dr. Daniel Kiprop', '+254700123459', 'male'),
  (gen_random_uuid(), 'dr.wanjiku@example.com', 'Dr. Mary Wanjiku', '+254700123460', 'female'),
  (gen_random_uuid(), 'dr.mutua@example.com', 'Dr. Peter Mutua', '+254700123461', 'male');

-- Now add sample doctors using the profile user_ids
INSERT INTO public.doctors (
  user_id, 
  specialty, 
  location, 
  experience_years, 
  consultation_fee, 
  license_number, 
  hospital_affiliation, 
  education, 
  bio,
  available_from,
  available_to,
  working_days,
  is_verified,
  is_available,
  rating,
  total_reviews
) VALUES
  (
    (SELECT user_id FROM profiles WHERE email = 'dr.smith@example.com'),
    'General Practitioner',
    'Nairobi',
    8,
    2500,
    'KMP001234',
    'Nairobi Hospital',
    'MBChB - University of Nairobi, MMed Family Medicine - Aga Khan University',
    'Experienced general practitioner with a focus on preventive care and family medicine. Committed to providing comprehensive healthcare to patients of all ages.',
    '08:00:00',
    '18:00:00',
    '{1,2,3,4,5,6}',
    true,
    true,
    4.8,
    156
  ),
  (
    (SELECT user_id FROM profiles WHERE email = 'dr.johnson@example.com'),
    'Cardiologist',
    'Nairobi',
    12,
    5000,
    'KMP001235',
    'Aga Khan University Hospital',
    'MBChB - University of Nairobi, MMed Internal Medicine, Fellowship in Cardiology - Harvard Medical School',
    'Board-certified cardiologist specializing in interventional cardiology and heart disease prevention.',
    '09:00:00',
    '17:00:00',
    '{1,2,3,4,5}',
    true,
    true,
    4.9,
    203
  ),
  (
    (SELECT user_id FROM profiles WHERE email = 'dr.ochieng@example.com'),
    'Pediatrician',
    'Mombasa',
    6,
    3000,
    'KMP001236',
    'Coast General Hospital',
    'MBChB - Moi University, MMed Pediatrics - University of Nairobi',
    'Dedicated pediatrician with expertise in child development and pediatric emergency care.',
    '07:30:00',
    '16:30:00',
    '{1,2,3,4,5}',
    true,
    true,
    4.7,
    98
  ),
  (
    (SELECT user_id FROM profiles WHERE email = 'dr.kiprop@example.com'),
    'Orthopedic Surgeon',
    'Eldoret',
    10,
    4500,
    'KMP001237',
    'Moi Teaching and Referral Hospital',
    'MBChB - Moi University, MMed Surgery, Fellowship in Orthopedics - University of Cape Town',
    'Specialized orthopedic surgeon with expertise in sports medicine and joint replacement surgery.',
    '08:00:00',
    '17:00:00',
    '{1,2,3,4,5}',
    true,
    true,
    4.6,
    87
  ),
  (
    (SELECT user_id FROM profiles WHERE email = 'dr.wanjiku@example.com'),
    'Dermatologist',
    'Nakuru',
    7,
    3500,
    'KMP001238',
    'Nakuru Level 5 Hospital',
    'MBChB - University of Nairobi, MMed Dermatology - Makerere University',
    'Expert dermatologist specializing in skin cancer detection and cosmetic dermatology.',
    '09:00:00',
    '16:00:00',
    '{1,2,3,4,5}',
    true,
    true,
    4.8,
    134
  ),
  (
    (SELECT user_id FROM profiles WHERE email = 'dr.mutua@example.com'),
    'Neurologist',
    'Kisumu',
    9,
    4000,
    'KMP001239',
    'Jaramogi Oginga Odinga Teaching and Referral Hospital',
    'MBChB - University of Nairobi, MMed Internal Medicine, Fellowship in Neurology - Johns Hopkins',
    'Neurologist with expertise in stroke management and neurodegenerative diseases.',
    '08:30:00',
    '17:30:00',
    '{1,2,3,4,5}',
    true,
    true,
    4.7,
    76
  );