// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmdbbeemnvhxtmtgzevj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtZGJiZWVtbnZoeHRtdGd6ZXZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Mjk2NDcsImV4cCI6MjA3MjMwNTY0N30.5Uc0f_q8_9fHTAyn_uFv5ApJwepkZkbwRBBBaOFC7X8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});